package org.codehaus.mojo.license.spdx;

/*
 * #%L
 * License Maven Plugin
 * %%
 * Copyright (C) 2019 Codehaus
 * %%
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as
 * published by the Free Software Foundation, either version 3 of the
 * License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Lesser Public License for more details.
 *
 * You should have received a copy of the GNU General Lesser Public
 * License along with this program.  If not, see
 * <http://www.gnu.org/licenses/lgpl-3.0.html>.
 * #L%
 */

/**
 * A class generated by GenerateSpdxLicenseList.groovy from
 * <a href="https://raw.githubusercontent.com/spdx/license-list-data/v3.5/json/licenses.json">
 * https://raw.githubusercontent.com/spdx/license-list-data/v3.5/json/licenses.json</a>
 */
public class SpdxLicenseListDataTest
{
    @org.junit.Test
    public void getInstance()
    {
        SpdxLicenseList list = SpdxLicenseList.getLatest();
        org.junit.Assert.assertEquals( 388, list.getLicenses().size() );
    }
}
